# -*- coding: utf-8 -*-
"""
/***************************************************************************
 altituteCorrector
                                 A QGIS plugin
 A processing plugin for altitude correction
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-08-30
        copyright            : (C) 2022 by Morten Sickel
        email                : morten@sickel.net
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Morten Sickel'
__date__ = '2022-08-30'
__copyright__ = '(C) 2022 by Morten Sickel'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load altituteCorrector class from file altituteCorrector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .altitude_corrector_processing import altituteCorrectorPlugin
    return altituteCorrectorPlugin()
